experiment_type: "utility+privacy" # choices=["utility", "utility+privacy", "compression", "compression+privacy"]
beta: 0.3

mine:
  utility_stats_network_model_name: "MINE_Model"
  utility_stats_network_model_params: {in_dim: 65, hidden_dims: [64, 32]}
  privacy_stats_network_model_name: "MINE_Model"
  privacy_stats_network_model_params: {in_dim: 65, hidden_dims: [64, 32]}
  use_prev_epochs_mi_model: false
  mine_batch_size: -1 # -1 means all data
  mine_epochs_privacy: -1
  mine_epochs_utility: -1
  mine_trainer_patience: 200